---
version: "0.1.0"
name: "restmpl"
db:
  dataDir: "/home/musti/naivary/projects/restmpl/"
fs:
  basepath: "/home/musti/restmpl"
  # maxSize of a file in bytes.
  # Default: 12MB
  maxSize: 12582912
  formKey: "file"
  # Cache duration of a file.
  # Default: 1 minute
  ttl: 1m
  dataDir: "/tmp/badger"
server:
  crt: ./configs/cert/localhost.crt
  key: ./configs/cert/localhost.key
  host: "localhost"
  port: 8080
  addr: ":8080"
  timeout:
    readHeader: 2s
    write: 2s
    idle: 10s
    request: 20s
  maxHeaderBytes: 1024
jwt:
  issuer: "https://api.auth.com"
  expiration: 5m
