---
version: "v0.1.0"
name: "instance"
fs:
  basepath: "/home/musti/instance_example"
  # maxSize of a file in bytes.
  # Default: 12MB
  maxSize: 12582912
  formKey: "file"
  # Cache duration of a file.
  # Default: 1 minute
  ttl: 1m
db: "/home/musti"
