---
version: "v0.1.0"
name: "instance"
fs:
  base: "/home/musti/instance_example"
  # maxSize of a file in bytes.
  # Default is 12MB
  maxSize: 12582912
  formKey: "file"
  # cache duration of a file.
  # Default: 1 minute
  ttl: 1m
db: "/home/musti"
server:
  timeout:
    readHeader: 30s
    write: 10s
    idle: 10s
  header:
    limit: 1000
