---
version: "0.1.0"
name: "instance"
dataDir: "."
fs:
  basepath: "/home/musti/instance_example"
  # maxSize of a file in bytes.
  # Default: 12MB
  maxSize: 12582912
  formKey: "file"
  # Cache duration of a file.
  # Default: 1 minute
  ttl: 1m
server:
  crt: ./configs/cert/localhost.crt
  key: ./configs/cert/localhost.key
  addr: ":8080"
  timeout:
    readHeader: 2s
    write: 2s
    idle: 10s
  maxHeaderBytes: 1024
logs:
  # maxSize of a log file before a
  # rotation should be applied (in bytes)
  # default: 12582912 (12 MB)
  # maxSize: 12582912
  maxSize: 500
  maxBackups: 3
  compress: true
